name: Publish to PyPI

on:
  release:
    types: [created]

env:
  LATEST_PYTHON_VERSION: 3.13

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.LATEST_PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          rm -rf dist
          python -m build

      - name: Publish package to PyPI
        run: |
          pip install twine
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*

      - name: Attach binaries to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: dist/*
